# Program for  Gauss-Seidel method.



Given is a nxn matrix A and a nx1 column matrix b 

In [348]:
#importing libraries 
import numpy as np
import pandas as pd
import sys

In [349]:
#definition of matrix multiplication from HW1
def multiply_matrix(mat1, mat2):
    dim1 = mat1.shape;       #dimension of matrix 1 
    dim2 = mat2.shape;       #dimension of matrix 2 


    #Check whether matrix are multiplicable  if not it will return to command
    if dim1[1] != dim2[0]:
        print('Matrix is not multiplicable');
        sys.exit()


    #Creating a ans matrix of length of rows of mat1 x length of column of mat2
    mat_ans = np.zeros((dim1[0],dim2[1]))

    #Running the loop to with the basic arithmatic logic to multiply two matrices 
    for i in range(0,dim1[0]):
        for k in range(0,dim2[1]):
            temp = 0 
            for l in range(0,dim2[0]):
                temp  = temp + mat1[i][l] * mat2[l][k]
            mat_ans[i][k] = temp
    return mat_ans

In [350]:
#definition for calculating the norm of the matrix ( matA * u - b)
def norm(mat1,mat2,mat3):
    dim1 = mat1.shape[0]
    dim2 = mat3.shape[0]
    if dim1 != dim2:                               #Check if matrix A and b are compatible 
        print('Error in matrix input');
        sys.exit()
    mat = multiply_matrix(matA,u)  
    
    #calculating norm with basic arithmatic logic
    ans = 0
    for j in range(dim1):
        ans = ans + abs(mat[j] - mat3[j])         
    return ans

##  Gauss-Seidel function

Important Note:

The u matrix is updated for every iteration, so the previous u(k-1) update is done is matrix already, so there is no need to break the correction term for previous updated value and current value of u matrix


In [351]:
#Function for Gauss Seidel method using basic arithmatic logic 
#It takes input of the main matrix A, matrix b,dimension n and the guess value

def Gau_Sed(matA,matb,u):
    n = matA.shape[0]
    while norm(matA,u,matb) > 1e-5:       #while function running till the norm converge
        
        
        #basic arithmatic logic for Gauss Siedel method 
        for i in range(n):
            f = 0
            for j in range(n):
                f = f  + matA[i][j] * u[j][0]
            r = matb[i][0] - f
            u[i][0] = u[i][0] + r/matA[i][i]
            r = 0
            print(norm(matA,u,matb))
           
        
        #Check if the matrix in diverging 
        if norm(matA,u,matb) > 1e10:
            break;
            print('Oops matrix did not converge');
            sys.exit()
    return u
  

### Checking for a test matrix

In [352]:
#import matrix A
df1 = pd.read_csv('mat A_test.csv',header = None,dtype = float)
matA = np.array(df1)
matA

array([[10.,  1.,  1.,  1.],
       [ 4., -5.,  2.,  2.],
       [ 0., -1.,  6., -5.],
       [ 1., -2., -2.,  9.]])

In [353]:
#import matrix b 
df2 = pd.read_csv('mat b_test.csv',header = None,dtype = float)
matb = np.array(df2)
matb

array([[40.],
       [20.],
       [36.],
       [11.]])

In [354]:
#size of nxn matrix 
n = matA.shape[0]
n

4

In [355]:
if matb.shape[0] != n:
    print("There is error in matrix input");
    sys.exit()

In [356]:
#guess value
guess = 50

In [357]:
#create the u matrix for storing the guess value
#The guess value is same for all variables
u = np.full((n,1),guess,dtype = float)  
u

array([[50.],
       [50.],
       [50.],
       [50.]])

In [358]:
Gau_Sed(matA,matb,u)

[378.]
[309.6]
[294.2]
[255.48888889]
[189.82444444]
[182.78088889]
[156.68103704]
[148.75460082]
[95.36380412]
[85.03887638]
[76.71269158]
[72.11166831]
[41.88389176]
[38.57317939]
[34.18720794]
[32.21847669]
[19.65343711]
[17.88478924]
[15.94940522]
[15.01889352]
[8.99398685]
[8.21839205]
[7.31369984]
[6.88880779]
[4.15207502]
[3.78865564]
[3.37400904]
[3.17771461]
[1.91104608]
[1.7446185]
[1.55330188]
[1.46297694]
[0.88048706]
[0.80367597]
[0.71560334]
[0.67398397]
[0.40552994]
[0.37017339]
[0.32959782]
[0.31042954]
[0.18679901]
[0.1705095]
[0.15182101]
[0.14299145]
[0.08604163]
[0.07853901]
[0.06993061]
[0.06586363]
[0.03963224]
[0.03617633]
[0.0322112]
[0.03033788]
[0.0182552]
[0.01666337]
[0.01483696]
[0.01397408]
[0.00840863]
[0.00767541]
[0.00683414]
[0.00643668]
[0.00387315]
[0.00353541]
[0.00314791]
[0.00296483]
[0.00178403]
[0.00162846]
[0.00144998]
[0.00136565]
[0.00082175]
[0.0007501]
[0.00066788]
[0.00062904]
[0.00037851]
[0.00034551]
[0.00030764]
[0.00028975]
[0.00017435

array([[2.30434748],
       [3.30434841],
       [9.7786568 ],
       [3.8735181 ]])

In [359]:
u 

array([[2.30434748],
       [3.30434841],
       [9.7786568 ],
       [3.8735181 ]])

In [360]:
print('Solution for the given linear equations are:')
for i in range(n):
    print(u[i][0])

Solution for the given linear equations are:
2.304347484859443
3.304348410504691
9.778656797018355
3.873518103354072


## Checking for given matrix

In [361]:
#import matrix A
df1 = pd.read_csv('mat A_given.csv',header = None,dtype = float)
matA = np.array(df1)
matA

array([[4., 1., 1., 1.],
       [1., 4., 1., 1.],
       [1., 1., 4., 1.],
       [1., 1., 1., 4.]])

In [362]:
#import matrix b 
df2 = pd.read_csv('mat b_given.csv',header = None,dtype = float)
matb = np.array(df2)
matb

array([[7.],
       [7.],
       [7.],
       [7.]])

In [363]:
#size of nxn matrix 
n = matA.shape[0]
n

4

In [364]:
if matb.shape[0] != n:
    print("There is error in matrix input");
    sys.exit()

In [365]:
#guess value
guess = 10

In [366]:
#create the u matrix for storing the guess value
#The guess value is same for all variables
u = np.full((n,1),guess,dtype = float)  
u

array([[10.],
       [10.],
       [10.],
       [10.]])

In [367]:
Gau_Sed(matA,matb,u)

[141.75]
[82.6875]
[56.109375]
[49.46484375]
[15.68847656]
[13.51977539]
[10.57818604]
[5.31504822]
[4.66256332]
[2.74241924]
[2.40946269]
[1.03008574]
[0.74164112]
[0.5951397]
[0.27949665]
[0.26955473]
[0.14132849]
[0.12156796]
[0.06415201]
[0.03649946]
[0.0329738]
[0.01656685]
[0.01533591]
[0.00732024]
[0.00610808]
[0.00381747]
[0.00186349]
[0.00183781]
[0.00093511]
[0.0008368]
[0.00039129]
[0.00029964]
[0.00021958]
[0.00010983]
[0.00010467]
[5.10239657e-05]
[4.41970169e-05]
[2.40674804e-05]
[1.41552645e-05]
[1.22689003e-05]
[6.29982474e-06]
[5.81403269e-06]
[2.70288102e-06]
[2.26230735e-06]


array([[1.00000011],
       [1.00000028],
       [1.00000004],
       [0.99999989]])

In [368]:
u

array([[1.00000011],
       [1.00000028],
       [1.00000004],
       [0.99999989]])

In [369]:
print('Solution for the given linear equations are:')
for i in range(n):
    print(u[i][0])

Solution for the given linear equations are:
1.0000001149280153
1.0000002768586993
1.000000039128971
0.9999998922710787


# END