# Program for  Gauss-Seidel method.

HW - 5

Name: Arush Kumar Singh

Roll No: 190182



## Defining Functions 

In [669]:
#importing libraries 
import numpy as np
import pandas as pd
import sys

In [670]:
#definition of matrix multiplication from HW1
def multiply_matrix(mat1, mat2):
    dim1 = mat1.shape;       #dimension of matrix 1 
    dim2 = mat2.shape;       #dimension of matrix 2 


    #Check whether matrix are multiplicable  if not it will return to command
    if dim1[1] != dim2[0]:
        print('Matrix is not multiplicable');
        sys.exit()


    #Creating a ans matrix of length of rows of mat1 x length of column of mat2
    mat_ans = np.zeros((dim1[0],dim2[1]))

    #Running the loop to with the basic arithmatic logic to multiply two matrices 
    for i in range(0,dim1[0]):
        for k in range(0,dim2[1]):
            temp = 0 
            for l in range(0,dim2[0]):
                temp  = temp + mat1[i][l] * mat2[l][k]
            mat_ans[i][k] = temp
    return mat_ans

In [671]:
#norm of a mxn matrix
def norm(A):
    m = A.shape[0]
    n = A.shape[1]
    sum = 0
    for i in range(m):
        for j in range(n):
            sum = sum + A[i][j]*A[i][j]
    sum = pow(sum,0.5)
    return sum

In [672]:
#determinant of a 3x3 matrix
def det(A):
    n = A.shape[0]
    if n == 2:
        return A[0][0]*A[1][1] - A[1][0]*A[0][1]
    total = 0
    for i in range (n):
        dub = np.delete(A,0,0)                                         #removing ith row
        dub = np.delete(dub,i,1)                                       #removing ith column
        total = total + pow(-1,i)*A[0][i]*det(dub)                     #calculation determinanat from first row
    return total
        

In [673]:
#cramers rule function of a 3 variable linear equation
#takes input as main marix and b matrix of Au = b and returns a 3x1 matrix of solution vector u
#this code is only valid for nxn A matrix s.t. n <= 3
def cramers(matA,v_0):
    n = matA.shape[0]
    u = np.full((n,1),0,dtype = float) 
    d = det(matA)
    if d == 0 :
        print('Unexpected singular matrix');
        sys.exit()
    for i in range(n):
        dx = np.delete(matA,i,1)
        dx = np.concatenate((dx, v_0), axis=1)
        u[i][0] = pow(-1,i+n-1)*det(dx)/d
    return u

In [674]:
#calcualte error between two nx1 matrix
def error(A,B):
    m = A.shape[0]
    n = B.shape[0]
    if m != n :
        print('Error in matrix input');
        sys.exit()
    u = np.full((n,1),0,dtype = float)  
    for i in range(n):
        u[i][0] = abs(A[i][0]) - abs(B[i][0])
    return norm(u)

In [675]:
#Power method function to return the eigen vector correspoinding to largest eigen value
#The function takes input as original matrix MatA, the guess matrix v_0 and the maximum error allowed 
def pow_med(matA,v_0,e):
    q = multiply_matrix(matA,v_0)
    v_1 = q/norm(q)
    while error(v_1,v_0) > e:
        v_0 = v_1;
        p = multiply_matrix(matA,v_0);
        v_1 = p/norm(p);
        #print(error(v_1,v_0))
    
        #Check if the matrix in diverging 
        if error(v_1,v_0) > 1e10:
            break;
            print('Oops matrix did not converge');
            sys.exit()
    #print(v_1)
    return v_1

In [676]:
#Inverse power method function to return the eigen vector correspoinding to largest eigen value
#The function takes input as original matrix MatA, the guess matrix v_0 and the maximum error allowed 
def inv_pow_med(matA,v_0,e):
    q = cramers(matA,v_0)
    v_1 = q/norm(q)
    while error(v_1,v_0) > e:
        v_0 = v_1
        p = cramers(matA,v_0)
        v_1 = p/norm(p);
    return v_1

### Checking the functions for a test value 


##### A. For largest eigen value

In [677]:
#import matrix A
df1 = pd.read_csv('mat A_test.csv',header = None,dtype = float)
matA = np.array(df1)
matA

array([[7., 3.],
       [6., 4.]])

In [678]:
#max error allowed
e = 1e-8
e

1e-08

In [679]:
#create the u matrix for storing the guess value
v_0 = np.array([[1],[0]])
#np.full((n,1),guess,dtype = float)  
v_0

array([[1],
       [0]])

In [680]:
#eigen vector corresponding to maximum(in absolute value) eigen value
v_1 = pow_med(matA,v_0,e)
v_1

array([[0.70710678],
       [0.70710678]])

In [681]:
#maximum(in absolute value) eigen value 
lembda_1 = norm(multiply_matrix(matA,v_1))/norm(v_1)
lembda_1

10.000000002250001

##### B. For smallest eigen value

In [682]:
#create the u matrix for storing the guess value
v_0 = np.array([[1],[0]])
v_0

array([[1],
       [0]])

In [683]:
#Eigen vector corresponding to Minimum(in absolute value) eigen vector
v_2 = inv_pow_med(matA,v_0,e)
v_2 = v_2/norm(v_2)
v_2

array([[ 0.4472136 ],
       [-0.89442719]])

In [684]:
#Minimum(in absolute value) eigen vector
lembda_2 = norm(multiply_matrix(matA,v_2))/norm(v_2)
lembda_2

0.99999999964

## Homework problem for Leslie Matrix

##### A. For largest eigen value

In [685]:
#import matrix A
df1 = pd.read_csv('mat A_given.csv',header = None,dtype = float)
matA = np.array(df1)
matA

array([[0. , 2.3, 0.4],
       [0.6, 0. , 0. ],
       [0. , 0.3, 0. ]])

In [686]:
#max error allowed
e = 1e-8
e

1e-08

In [687]:
#create the u matrix for storing the guess value
#The guess value is same for all variables
v_0 = np.array([[1],[0],[0]])
#np.full((n,1),guess,dtype = float)  
v_0

array([[1],
       [0],
       [0]])

In [688]:
#eigen vector corresponding to maximum(in absolute value) eigen value
v_1 = pow_med(matA,v_0,e)
v_1

array([[0.88888889],
       [0.44444445],
       [0.11111111]])

In [689]:
#maximum(in absolute value) eigen value 
lembda_1 = norm(multiply_matrix(matA,v_1))/norm(v_1)
lembda_1

1.2000000080552766

##### B. For smallest eigen value

In [690]:
#create the u matrix for storing the guess value
v_0 = np.array([[1],[0],[0]])
v_0

array([[1],
       [0],
       [0]])

In [691]:
#Eigen vector corresponding to Minimum(in absolute value) eigen vector
v_2 = inv_pow_med(matA,v_0,e)
v_2 = v_2/norm(v_2)
v_2

array([[-0.01495588],
       [ 0.17165196],
       [-0.98504412]])

In [692]:
#Minimum(in absolute value) eigen vector
lembda_2 = norm(multiply_matrix(matA,v_2))/norm(v_2)
lembda_2

0.052277442479281205

# END