##  Program for the naive Gaussian elimination.


Given is a nxn matrix A and a nx1 column matrix b 

In [31]:
#importing libraries 
import numpy as np
import pandas as pd
import sys

In [32]:
#import matrix A
df1 = pd.read_csv('mat A.csv',header = None,dtype = float)
matA = np.array(df1)
matA

array([[ 1.,  1.,  1.,  1.],
       [ 4., -5.,  2.,  2.],
       [ 7., -1.,  6., -5.],
       [ 1., -2., -2.,  9.]])

In [33]:
#import matrix b 
df2 = pd.read_csv('mat b.csv',header = None,dtype = float)
matb = np.array(df2)
matb

array([[40.],
       [20.],
       [36.],
       [11.]])

In [34]:
#size of nxn matrix 
n = matA.shape[0]
n

4

In [35]:
if matb.shape[0] != n:
    print("There is error in matrix input");
    sys.exit()

In [36]:
#create answer matrix to store answer
x = np.zeros([n,1])
x

array([[0.],
       [0.],
       [0.],
       [0.]])

###  Forward Elimination Starts

In [37]:
#forward elimination using basic arithmatic logic 
for k in range(n-1):
    for i in range(k+1,n):
        if matA[k][k] == 0:
            print("This cannot be solved using naive gaussian elimination due to unexpected 0 pivot element");
            sys.exit()
        factor = matA[i][k]/matA[k][k]
        matb[i][0]  = matb[i][0] - (factor * matb[k][0])
        for j in range(k,n):
            matA[i][j] = matA[i][j] - (factor * matA[k][j])
if matA[n-1][n-1] == 0:
    print("This cannot be solved using naive gaussian elimination due to unexpected 0 pivot element");
    sys.exit()

In [38]:
matA

array([[  1.        ,   1.        ,   1.        ,   1.        ],
       [  0.        ,  -9.        ,  -2.        ,  -2.        ],
       [  0.        ,   0.        ,   0.77777778, -10.22222222],
       [  0.        ,   0.        ,   0.        , -22.        ]])

In [39]:
matb

array([[  40.        ],
       [-140.        ],
       [-119.55555556],
       [-341.        ]])

### Forward Eliminations ends , Back substitution starts

In [40]:
#calculating last variable
x[n-1] = matb[n-1]/matA[n-1][n-1]
x

array([[ 0. ],
       [ 0. ],
       [ 0. ],
       [15.5]])

In [41]:
#arithmatic logic for back substitution and storing the answer in x 
for i in reversed(range(0,n-1)):
    add = 0;
    for j in range(i+1,n):
        add = add + matA[i][j]*x[j][0]
    x[i][0] = (matb[i][0] - add)/matA[i][i]
x

array([[-26.5],
       [  1. ],
       [ 50. ],
       [ 15.5]])

In [42]:
print('Solution for the given linear equations are:')
for i in range(n):
    print(x[i][0])

Solution for the given linear equations are:
-26.500000000000014
0.9999999999999937
50.00000000000002
15.500000000000002



# Program for given matrix

Same code will be repeated by taking "mat A = mat g" and "mat b = mat bg"

In [13]:
#import given matrix "Mat g.csv"
df3 = pd.read_csv('Mat g.csv',header = None,dtype = float)
matA = np.array(df3)
matA

array([[4., 1., 1., 1.],
       [1., 4., 1., 1.],
       [1., 1., 4., 1.],
       [1., 1., 1., 4.]])

In [14]:
#import matrix b "Mat bg.csv"
df2 = pd.read_csv('mat bg.csv',header = None,dtype = float)
matb = np.array(df2)
matb

array([[7.],
       [7.],
       [7.],
       [7.]])

In [15]:
#size of nxn matrix 
n = matA.shape[0]
n

4

In [16]:
#create answer matrix to store answer
x = np.zeros([n,1])
x

array([[0.],
       [0.],
       [0.],
       [0.]])

### Forward elimination starts

In [17]:
#forward elimination using basic arithmatic logic 
for k in range(n-1):
    for i in range(k+1,n):
        if matA[k][k] == 0:
            print("This cannot be solved using naive gaussian elimination due to unexpected 0 pivot element");
            sys.exit()
        factor = matA[i][k]/matA[k][k]
        matb[i][0]  = matb[i][0] - (factor * matb[k][0])
        for j in range(k,n):
            matA[i][j] = matA[i][j] - (factor * matA[k][j])
if matA[n-1][n-1] == 0:
    print("This cannot be solved using naive gaussian elimination due to unexpected 0 pivot element");
    sys.exit()

    

In [18]:
matA

array([[4.  , 1.  , 1.  , 1.  ],
       [0.  , 3.75, 0.75, 0.75],
       [0.  , 0.  , 3.6 , 0.6 ],
       [0.  , 0.  , 0.  , 3.5 ]])

In [19]:
matb

array([[7.  ],
       [5.25],
       [4.2 ],
       [3.5 ]])

### Forward Eliminations ends , Back substitution starts


In [20]:
x[n-1] = matb[n-1]/matA[n-1][n-1]
x


array([[0.],
       [0.],
       [0.],
       [1.]])

In [21]:
for i in reversed(range(0,n-1)):
    add = 0;
    for j in range(i+1,n):
        add = add + matA[i][j]*x[j][0]
    x[i][0] = (matb[i][0] - add)/matA[i][i]
x

array([[1.],
       [1.],
       [1.],
       [1.]])

In [22]:
print('Solution for the given linear equations are:')
for i in range(n):
    print(x[i][0])

Solution for the given linear equations are:
1.0
1.0
1.0
1.0


#  END